Spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: usr_fabric
    password: Test1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: none
  logging:
    level:
      org:
        hibernate:
          type: trace
